# Generated by Django 4.0.6 on 2022-08-07 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trituradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conica', 'Conica'), ('mandíbula', 'Mandibulas')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('aberturaEntrada', models.CharField(max_length=50)),
                ('aberturaCierre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='trituradoras')),
            ],
            options={
                'verbose_name': 'trituradora',
                'verbose_name_plural': 'trituradoras',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jugador',
                'verbose_name_plural': 'jugadores',
            },
        ),
        migrations.CreateModel(
            name='CurvaGranulometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.FloatField()),
                ('porcentaje', models.FloatField()),
                ('trituradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.trituradora')),
            ],
            options={
                'verbose_name': 'curva',
                'verbose_name_plural': 'curvas',
            },
        ),
    ]
