# Generated by Django 4.0.6 on 2022-08-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_patrimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('conica', 'Conica'), ('mandíbula', 'Mandibulas')], max_length=20),
        ),
    ]
