# Generated by Django 4.0.6 on 2022-08-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_alter_trituradora_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('dureza', models.CharField(choices=[('medio', 'Medio'), ('blando', 'Blando'), ('duro', 'Duro')], max_length=20)),
                ('caudal', models.FloatField()),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('mandíbula', 'Mandibulas'), ('conica', 'Conica')], max_length=20),
        ),
    ]
