# Generated by Django 4.0.6 on 2022-08-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_material_alter_trituradora_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='materiales'),
        ),
    ]
