# Generated by Django 4.0.6 on 2022-08-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_material_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('blando', 'Blando'), ('duro', 'Duro'), ('medio', 'Medio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('conica', 'Conica'), ('mandíbula', 'Mandibulas')], max_length=20),
        ),
        migrations.CreateModel(
            name='CurvaGranulometricaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.FloatField()),
                ('porcentaje', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.material')),
            ],
            options={
                'verbose_name': 'curva material',
                'verbose_name_plural': 'curvas material',
            },
        ),
    ]
