# Generated by Django 4.0.6 on 2022-08-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_alter_material_dureza_alter_trituradora_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('medio', 'Medio'), ('blando', 'Blando'), ('duro', 'Duro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('mandíbula', 'Mandibulas'), ('conica', 'Conica')], max_length=20),
        ),
    ]
