# Generated by Django 4.0.6 on 2022-08-21 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0008_alter_material_dureza_alter_trituradora_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('duro', 'Duro'), ('blando', 'Blando'), ('medio', 'Medio')], max_length=20),
        ),
        migrations.CreateModel(
            name='PatrimonioMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
