# Generated by Django 4.0.6 on 2022-08-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_alter_material_dureza_patrimoniomateriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
                ('tamanoDesde', models.FloatField()),
                ('tamanoHasta', models.FloatField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('blando', 'Blando'), ('medio', 'Medio'), ('duro', 'Duro')], max_length=20),
        ),
    ]
