# Generated by Django 4.0.6 on 2022-08-21 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0010_demanda_alter_material_dureza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanda',
            options={'verbose_name': 'demanda', 'verbose_name_plural': 'demanda'},
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('conica', 'Conica'), ('mandíbula', 'Mandibulas')], max_length=20),
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.patrimoniomateriales')),
                ('primerEtapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primerEtapa', to='mercado.patrimonio')),
                ('segundaEtapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundaEtapa', to='mercado.patrimonio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
