# Generated by Django 4.0.6 on 2022-08-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0011_alter_demanda_options_alter_trituradora_tipo_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('blando', 'Blando'), ('duro', 'Duro'), ('medio', 'Medio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('mandíbula', 'Mandibulas'), ('conica', 'Conica')], max_length=20),
        ),
    ]
