# Generated by Django 4.0.6 on 2022-08-21 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercado', '0012_alter_material_dureza_alter_trituradora_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('medio', 'Medio'), ('duro', 'Duro'), ('blando', 'Blando')], max_length=20),
        ),
    ]
