# Generated by Django 4.0.6 on 2022-09-10 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0016_alter_layout_primeretapa_alter_layout_segundaetapa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='caudal',
        ),
        migrations.AddField(
            model_name='patrimoniomateriales',
            name='caudal',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demanda',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.material'),
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('mandíbula', 'Mandibulas'), ('conica', 'Conica')], max_length=20),
        ),
    ]
