# Generated by Django 4.0.6 on 2022-09-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0017_remove_material_caudal_patrimoniomateriales_caudal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('duro', 'Duro'), ('blando', 'Blando'), ('medio', 'Medio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('conica', 'Conica'), ('mandíbula', 'Mandibulas')], max_length=20),
        ),
    ]
