# Generated by Django 4.0.6 on 2022-09-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0018_alter_material_dureza_alter_trituradora_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curvagranulometricamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.patrimoniomateriales'),
        ),
    ]
