# Generated by Django 4.0.6 on 2022-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0019_alter_curvagranulometricamaterial_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='trituradora',
            name='caudalBlando',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trituradora',
            name='caudalDuro',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trituradora',
            name='caudalMedio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trituradora',
            name='manto',
            field=models.CharField(choices=[('medium', 'Medium'), ('ninguno', 'Ninguno'), ('extra-course', 'Extra-Course'), ('course', 'Course')], default='ninguno', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('medio', 'Medio'), ('duro', 'Duro'), ('blando', 'Blando')], max_length=20),
        ),
    ]
