# Generated by Django 4.1.6 on 2023-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0020_trituradora_caudalblando_trituradora_caudalduro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='valorActual',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='manto',
            field=models.CharField(choices=[('course', 'Course'), ('extra-course', 'Extra-Course'), ('medium', 'Medium'), ('ninguno', 'Ninguno')], max_length=20),
        ),
    ]
