# Generated by Django 4.1.6 on 2023-02-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0021_patrimonio_valoractual_alter_trituradora_manto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('blando', 'Blando'), ('duro', 'Duro'), ('medio', 'Medio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='manto',
            field=models.CharField(choices=[('medium', 'Medium'), ('extra-course', 'Extra-Course'), ('ninguno', 'Ninguno'), ('course', 'Course')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='tipo',
            field=models.CharField(choices=[('mandíbula', 'Mandibulas'), ('conica', 'Conica')], max_length=20),
        ),
    ]
