# Generated by Django 4.1.6 on 2023-02-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0022_alter_material_dureza_alter_trituradora_manto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='dureza',
            field=models.CharField(choices=[('duro', 'Duro'), ('medio', 'Medio'), ('blando', 'Blando')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trituradora',
            name='manto',
            field=models.CharField(choices=[('medium', 'Medium'), ('ninguno', 'Ninguno'), ('course', 'Course'), ('extra-course', 'Extra-Course')], max_length=20),
        ),
    ]
